// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obcikaideuwlqsbtagnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iY2lrYWlkZXV3bHFzYnRhZ25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjE1MDUsImV4cCI6MjA2NDQzNzUwNX0.zNN6BE8UBxL7iV6uYGbmpgjTnIB56hIHnmJir-ydHwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);